apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akscluster-backend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akscluster-backend"
  template:
    metadata:
      labels:
        app: "akscluster-backend"
    spec:
      containers:
        - name: "akscluster-backend"
          image: "aksregitery001.azurecr.io/akscluster"
          ports:
          - containerPort: 80