apiVersion: v1
kind: Service
metadata:
    name: "recogaks-backend"
    labels:
        app: "recogaks-backend"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "recogaks-backend"