apiVersion: v1
kind: Service
metadata:
    name: "recogaks-ecf8"
    labels:
        app: "recogaks-ecf8"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "recogaks-ecf8"